const Jsonator = require('../serialization/Jsonator.js');
const Logger = require('../util/Logger.js');
const config = require('../config.json');

/**
 * Used to remind guild members of their classes. 
 * Needs the remind text channels IDs configured in the config.json file.
 * 
 * @author Ismael Trentin
 * @version 2020.05.20
 */
class ClassReminder {

    /**
     * Instantiates a new ClassReminder object.
     */
    constructor() {
        this.logger = new Logger();
        this.jtor = new Jsonator('./data/students.json', './data/teachers.json', './data/modulez.json', './data/timetables/');
    }

    /**
     * Reminds all guild members of the guild guild of their classes.
     * 
     * @param {Guild} guild the guild wich to take the members from
     */
    remindClasses(guild) {
        let groups = this.jtor.getGroups();
        groups.forEach(g => {
            if (guild.available) {
                let channel = guild.channels.resolve(config["reminder-channels"].i2ac);
                this.remindNextClass(g, channel);
            } else {
                this.logger.log(`Guild ${g.name} is unavailable skipping...`, this.logger.categories.WARNING);
            }
        });
    }

    /**
     * Reminds
     * 
     * @param {} group 
     * @param {*} textChannel 
     */
    /*
    remindNextClass(group, textChannel) {
        this.jtor.getClassezFor(group)
            .then(cl => {
                let now = new Date();
                let h = now.getHours();
                let m = now.getMinutes();
                let remindClass;

                cl.forEach(c => {
                    if (c.start.h > h) {
                        remindClass = c;
                    }
                });
                if (remindClass) {
                    textChannel.send('', {
                        embed: {
                            title: 'Next Class Reminder',
                            color: [3, 123, 252],
                            thumbnail: {
                                //https://cdn.discordapp.com/avatars/707675789075939480/91adf2be9405bdbcd3ad96d301c10a24.png
                                url: 'https://cdn.discordapp.com/avatars/708026018861940897/e89d82126a71edee1e819c09f1712305.png',
                            },
                            fields: [
                                {
                                    name: 'Next class:',
                                    value: remindClass.name,
                                    inline: true,
                                },
                                {
                                    name: 'Starts at:',
                                    value: `${remindClass.start.h}:${remindClass.start.m}`,
                                    inline: true,
                                },
                                {
                                    name: 'Teacher:',
                                    value: remindClass.teacherfullname,
                                    inline: false,
                                },
                            ],
                            footer: {
                                text: 'Generated by cptbot',
                            }
                        },
                    }).catch(console.error);
                } else {
                    //this.logger.log('No more classes for group ' + group, this.logger.categories.WARNING);
                }
            })
            .catch(err => this.logger.log(err, this.logger.categories.ERROR));
    }*/

    remindNextClass(clazz, textChannel) {
        let now = new Date();
        let h = now.getHours();
        let m = now.getMinutes();
        if (clazz) {
            textChannel.send('', {
                embed: {
                    title: 'Next Class Reminder',
                    color: [3, 123, 252],
                    thumbnail: {
                        //https://cdn.discordapp.com/avatars/707675789075939480/91adf2be9405bdbcd3ad96d301c10a24.png
                        url: 'https://cdn.discordapp.com/avatars/708026018861940897/e89d82126a71edee1e819c09f1712305.png',
                    },
                    fields: [
                        {
                            name: 'Next class:',
                            value: clazz.name,
                            inline: true,
                        },
                        {
                            name: 'Starts at:',
                            value: `${clazz.start.h}:${clazz.start.m}`,
                            inline: true,
                        },
                        {
                            name: 'Teacher:',
                            value: clazz.teacher_full_name,
                            inline: false,
                        },
                    ],
                    footer: {
                        text: 'Generated by cptbot',
                    }
                },
            }).catch(console.error);
        } else {
            //this.logger.log('No more classes for group ' + group, this.logger.categories.WARNING);
        }
    }
}

module.exports = ClassReminder;